/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PongPanel.java
 *
 * Created on 12-Mar-2015, 11:34:29 AM
 */
package dpong;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

public class PongPanel extends javax.swing.JPanel{

    public static final int MAXHEIGHT = 600;
    public static final int MAXWIDTH = 800;
    public static final int MAXDEPTH = 1200;
    private static int mouseX;
    private static int mouseY;
    private static boolean click;
    public static Game game;

    /**
     * Creates new form PongPanel
     */
    public PongPanel(){
        initComponents();
        game = new Game();
        Timer myTimer = new Timer(30, new ActionListener(){
            public void actionPerformed(ActionEvent evt){

                formActionPerformed(evt);
            }

        });
        myTimer.start();
        this.setFocusable(true);
        this.requestFocusInWindow();
    }

    @Override
    public void paint(Graphics g){
        super.paint(g);
        game.paint(g);
    }

    private void formActionPerformed(ActionEvent evt){
        game.update(mouseX, mouseY, click);
        this.repaint();
        click = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        mouseX = evt.getX();
        mouseY = evt.getY();
    }//GEN-LAST:event_formMouseMoved

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        click = true;
    }//GEN-LAST:event_formMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
