/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PongFrame.java
 *
 * Created on 12-Mar-2015, 11:40:07 AM
 */
package dpong;

/**
 *
 * @author 133371
 */
public class PongFrame extends javax.swing.JFrame{

    /**
     * Creates new form PongFrame
     */
    public PongFrame(){
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        movingSquarePanel1 = new dpong.PongPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        movingSquarePanel1.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout movingSquarePanel1Layout = new javax.swing.GroupLayout(movingSquarePanel1);
        movingSquarePanel1.setLayout(movingSquarePanel1Layout);
        movingSquarePanel1Layout.setHorizontalGroup(
            movingSquarePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        movingSquarePanel1Layout.setVerticalGroup(
            movingSquarePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movingSquarePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(movingSquarePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 816, 638);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]){
        java.awt.EventQueue.invokeLater(new Runnable(){
            public void run(){
                new PongFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private dpong.PongPanel movingSquarePanel1;
    // End of variables declaration//GEN-END:variables

}
